export type FormCustomizations = {
  theme: "light" | "dark" | "custom";
  backgroundColor: string;
  color: string;
  buttonColor: string;
  buttonText: string;
  accentColor: string;
  pageWidth?: number;
  baseFontSize?: number;
  logo?: string;
  logoWidth?: number;
  logoHeight?: number;
  logoCornerRadius?: number;
  image?: string;
  imageHeight?: number;
  inputsWidthType?: "fixed" | "full" | "auto";
  inputsWidth?: number;
  inputsHeight?: number;
  inputsRadius?: number;
  inputsBackgroundColor: string;
  inputsTextColor: string;
  inputsBorderColor: string;
  inputsBorderWidth?: number;
  inputsPlaceholderColor: string;
  inputsMarginBottom?: number;
  inputsHorizontalPadding?: number;
};
