export type FormCustomizations = {
  theme: "light" | "dark" | "custom";
  backgroundColor: string;
  color: string;
  accentColor: string;
  pageWidth?: number;
  baseFontSize?: number;
  logo?: string;
  logoWidth?: number;
  logoHeight?: number;
  logoCornerRadius?: number;
  image?: string;
  imageHeight?: number;
  inputsWidthType?: "fixed" | "full" | "auto";
  inputsWidth?: number;
  inputsHeight?: number;
  inputsRadius?: number;
  inputsBackgroundColor: string;
  inputsTextColor: string;
  inputsBorderColor: string;
  inputsBorderWidth?: number;
  inputsPlaceholderColor: string;
  inputsMarginBottom?: number;
  inputsHorizontalPadding?: number;
  buttonWidth?: number;
  buttonWidthType?: "fixed" | "full" | "auto";
  buttonHeight?: number;
  buttonRadius?: number;
  buttonFontSize?: number;
  buttonColor: string;
  buttonText: string;
  buttonVerticalMargin?: number;
  buttonHorizontalPadding?: number;
  buttonAlignment?: "left" | "center" | "right";
};
