name = "formsmith-api"
main = "src/index.ts"
compatibility_date = "2025-01-12"

[observability.logs]
enabled = true

[[r2_buckets]]
binding = "FORMSMITH_CDN"
bucket_name = "formsmith-cdn"
preview_bucket_name = "dev-formsmith-cdn"